name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project
        run: |
          # Add your build commands here
          echo "Building the project..."

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: production file
          path: ./todo/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production file
          path: ./todo/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KEY }}
          publish_dir: ./todo/build